# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1245c3d9f2c4c80bc2640d4b6cadfe56"
name = "Test Plus"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
