api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cart"
type = "function"
uid = "67bb9686-dcaf-1977-b54e-c46889e0b29897d24df5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
